locations:
  1000:
    description:
      de:
        long: Inventory
        short: Inv
      en:
        long: Inventory
        short: Inv
  2000:
    description:
      de:
        long: Objects in use
        short: inUse
      en:
        long: Objects in use
        short: inUse
  1:
    description:
      de:
        long: vor einem riesigem Torbogen.
        short: Torbogen
      en:
        long: in front of a giant archway.
        short: archway
    directions: 
      - 0
      - 0
      - 2
      - 0
    coordinates:
      y: 11
      x: 0
  2:
    description:
      de:
        long: auf einer Blumenwiese.
        short: Blumenwiese
      en:
        long: on a wildflower meadow.
        short: meadow
    directions: 
      - 8
      - 0
      - 3
      - 1
    coordinates:
      y: 11
      x: 1
  3:
    description:
      de:
        long: an einem Seerosenteich.
        short: Seerosenteich
      en:
        long: at a lilly pond.
        short: pond
    directions: 
      - 9
      - 0
      - 0
      - 2
    coordinates:
      y: 11
      x: 2
  4:
    description:
      de:
        long: in einer trostlosen Einöde.
        short: Einöde
      en:
        long: in a grim dessert.
        short: dessert
    directions: 
      - 10
      - 0
      - 5
      - 0
    coordinates:
      y: 11
      x: 3
  5:
    description:
      de:
        long: in einem nebligem Moor.
        short: Moor
      en:
        long: in a foggy swamp.
        short: swamp
    directions: 
      - 11
      - 0
      - 0
      - 4
    coordinates:
      y: 11
      x: 4
  6:
    description:
      de:
        long: in einer feenhaften Grotte.
        short: Grotte
      en:
        long: in a fairylike grotto.
        short: grotto
    directions: 
      - 13
      - 0
      - 7
      - 0
    coordinates:
      y: 9
      x: 0
  7:
    description:
      de:
        long: an einer zerklüfteten Felswand.
        short: Felswand
      en:
        long: at a fissured cliff.
        short: cliff
    directions: 
      - 0
      - 8
      - 0
      - 0
    coordinates:
      y: 9
      x: 1
  8:
    description:
      de:
        long: in einem lichten Auwald.
        short: Auwald
      en:
        long: in a light-flooded lowland forest.
        short: forrest
    directions: 
      - 7
      - 2
      - 9
      - 0
    coordinates:
      y: 10
      x: 1
  9:
    description:
      de:
        long: auf einer blühenden Heide.
        short: Heide
      en:
        long: on a flourishing heath.
        short: heath
    directions: 
      - 15
      - 3
      - 10
      - 8
    coordinates:
      y: 10
      x: 2
  10:
    description:
      de:
        long: in einer verdorrten Steppe.
        short: Steppe
      en:
        long: in a sere steppe.
        short: steppe
    directions: 
      - 0
      - 4
      - 11
      - 9
    coordinates:
      y: 10
      x: 3
  11:
    description:
      de:
        long: auf dem Versammlungsplatz der Gnome.
        short: Versammlungsplatz
      en:
        long: on the haunt of the gnomes.
        short: haunt
    directions: 
      - 0
      - 5
      - 12
      - 10
    coordinates:
      y: 10
      x: 4
  12:
    description:
      de:
        long: in der Waffenkammer der Gnome.
        short: Waffenkammer
      en:
        long: in the armory of the gnomes.
        short: armory
    directions: 
      - 0
      - 0
      - 0
      - 11
    coordinates:
      y: 10
      x: 5
  13:
    description:
      de:
        long: in einer Tropfsteinhöhle.
        short: Tropfsteinhöhle
      en:
        long: in a flowstone cave.
        short: cave
    directions: 
      - 16
      - 6
      - 0
      - 0
    coordinates:
      y: 8
      x: 0
  14:
    description:
      de:
        long: am Fuß eines Berges.
        short: Berg
      en:
        long: at the bottom of a mountain.
        short: mountain
    directions: 
      - 17
      - 0
      - 15
      - 0
    coordinates:
      y: 8
      x: 1
  15:
    description:
      de:
        long: in der Schatzkammer der Elfen.
        short: Schatzkammer
      en:
        long: in the treasure chamber of the elves.
        short: chamber
    directions: 
      - 0
      - 9
      - 0
      - 14
    coordinates:
      y: 8
      x: 2
  16:
    description:
      de:
        long: auf einer Bergwiese.
        short: Bergwiese
      en:
        long: on a mountain hayfield.
        short: hayfield
    directions: 
      - 0
      - 13
      - 17
      - 0
    coordinates:
      y: 7
      x: 0
  17:
    description:
      de:
        long: an einer silbernen Quelle.
        short: Quelle
      en:
        long: at a dewy spring.
        short: spring
    directions: 
      - 0
      - 14
      - 18
      - 16
    coordinates:
      y: 7
      x: 1
  18:
    description:
      de:
        long: in einer Schlucht mit vielen Farnen.
        short: Schlucht
      en:
        long: in a gorge with many ferns.
        short: gorge
    directions: 
      - 24
      - 0
      - 19
      - 17
    coordinates:
      y: 7
      x: 2
  19:
    description:
      de:
        long: in einer Bärenhöhle.
        short: Bärenhöhle
      en:
        long: in a baer's den
        short: den
    directions: 
      - 25
      - 0
      - 20
      - 18
    coordinates:
      y: 7
      x: 3
  20:
    description:
      de:
        long: auf einer schwankenden Hängebrücke.
        short: Hängebrücke
      en:
        long: on a swinging rope bridge.
        short: bridge
    directions: 
      - 0
      - 0
      - 21
      - 19
    coordinates:
      y: 7
      x: 4
  21:
    description:
      de:
        long: an einem Wiesenhang.
        short: Wiesenhang
      en:
        long: at a hillside
        short: hillside
    directions: 
      - 26
      - 0
      - 0
      - 20
    coordinates:
      y: 7
      x: 5
  22:
    description:
      de:
        long: in einer Rosenlaube.
        short: Rosenlaube
      en:
        long: in a rose covered bower.
        short: bower
    directions: 
      - 27
      - 0
      - 23
      - 0
    coordinates:
      y: 6
      x: 0
  23:
    description:
      de:
        long: in einem verwilderten Park.
        short: Park
      en:
        long: in overgrown park.
        short: park
    directions: 
      - 0
      - 0
      - 24
      - 22
    coordinates:
      y: 6
      x: 1
  24:
    description:
      de:
        long: auf einem verschlungenen Weg.
        short: Weg
      en:
        long: on a braided path.
        short: path
    directions: 
      - 29
      - 18
      - 0
      - 23
    coordinates:
      y: 6
      x: 2
  25:
    description:
      de:
        long: an einer verfallenen Burgruine.
        short: Burgruine
      en:
        long: at a ruinous castle.
        short: castle
    directions: 
      - 30
      - 19
      - 0
      - 0
    coordinates:
      y: 6
      x: 3
  26:
    description:
      de:
        long: in einem sonnigen Obsthain.
        short: Obsthain
      en:
        long: on a sunny grove.
        short: grove
    directions: 
      - 32
      - 21
      - 0
      - 0
    coordinates:
      y: 6
      x: 5
  27:
    description:
      de:
        long: in einem Kräutergarten.
        short: Kräutergarten
      en:
        long: in a herbage garden.
        short: garden
    directions: 
      - 0
      - 22
      - 28
      - 0
    coordinates:
      y: 5
      x: 0
  28:
    description:
      de:
        long: in einer finsteren Hexenküche.
        short: Hexenküche
      en:
        long: in the dark kitchen of a witch.
        short: kitchen
    directions: 
      - 0
      - 0
      - 0
      - 27
    coordinates:
      y: 5
      x: 1
  29:
    description:
      de:
        long: im Hof einer verlassenen Burg.
        short: Burg
      en:
        long: in the coutyard of an abandoned castle.
        short: castle
    directions: 
      - 0
      - 0
      - 30
      - 0
    coordinates:
      y: 5
      x: 2
  30:
    description:
      de:
        long: in einem finsteren Burgverlies.
        short: Burgverlies
      en:
        long: in a dark castle dungeon.
        short: dungeon
    directions: 
      - 0
      - 25
      - 0
      - 0
    coordinates:
      y: 5
      x: 3
  31:
    description:
      de:
        long: in der Krone eines Baumes.\n++Ich kann nicht weit sehen.++
        short: Baumkrone
      en:
        long: in a tree top.\n++Ich can't see far.++
        short: tree
    directions: 
      - 0
      - 0
      - 0
      - 0
    coordinates:
      y: 9
      x: 3
  32:
    description:
      de:
        long: in einem feuchten Laubwald.
        short: Laubwald
      en:
        long: in a moist deciduous forest.
        short: forest
    directions: 
      - 0
      - 26
      - 0
      - 33
    coordinates:
      y: 3
      x: 5
  33:
    description:
      de:
        long: im Reich der Feen.
        short: Feenreich
      en:
        long: in the realm of the fairies.
        short: realm
    directions: 
      - 0
      - 34
      - 32
      - 0
    coordinates:
      y: 3
      x: 4
  34:
    description:
      de:
        long: in einer grauen Steinwüste.
        short: Steinwüste
      en:
        long: in a grey stone dessert.
        short: dessert
    directions: 
      - 33
      - 36
      - 37
      - 35
    coordinates:
      y: 4
      x: 4
  35:
    description:
      de:
        long: an einem breiten Fluss.\n++Am anderen Ufer bewegt sich etwas.++
        short: Fluss
      en:
        long: at a wide river.\n++There is movement on the other side.++
        short: river
    directions: 
      - 0
      - 0
      - 34
      - 0
    coordinates:
      y: 4
      x: 3
  36:
    description:
      de:
        long: auf einem dreckigem Pfad.
        short: Pfad
      en:
        long: on a muddy path.
        short: path
    directions: 
      - 34
      - 0
      - 5
      - 0
    coordinates:
      y: 5
      x: 4
  37:
    description:
      de:
        long: in einem Dornengestrüpp.\n++Ich finde mich nicht mehr zurecht.++
        short: Dornengestrüpp
      en:
        long: in a thicket.\n++I am lost.++
        short: thicket
    directions: 
      - 37
      - 38
      - 39
      - 34
    coordinates:
      y: 4
      x: 6
  38:
    description:
      de:
        long: in einem Dornengestrüpp.\n++Ich finde mich nicht mehr zurecht.++
        short: Dornengestrüpp
      en:
        long: in a thicket.\n++I am lost.++
        short: thicket
    directions: 
      - 37
      - 38
      - 38
      - 38
    coordinates:
      y: 5
      x: 6
  39:
    description:
      de:
        long: in einem Dornengestrüpp.\n++Ich finde mich nicht mehr zurecht.++
        short: Dornengestrüpp
      en:
        long: in a thicket.\n++I am lost.++
        short: thicket
    directions: 
      - 40
      - 39
      - 39
      - 37
    coordinates:
      y: 4
      x: 7
  40:
    description:
      de:
        long: auf einem Hohlweg.
        short: Hohlweg
      en:
        long: on a narrow pass.
        short: pass
    directions: 
      - 42
      - 39
      - 0
      - 0
    coordinates:
      y: 3
      x: 7
  41:
    description:
      de:
        long: in einem unheimlichen Wald.\n++Man sieht kaum einen Weg. Ob hier ein\nDrache haust?!++
        short: Wald
      en:
        long: in a scary wood.\n++You almost see no path. Is this a place\nwhere dragons live?!++
        short: wood
    directions: 
      - 43
      - 41
      - 42
      - 41
    coordinates:
      y: 2
      x: 6
  42:
    description:
      de:
        long: in einem unheimlichen Wald.\n++Man sieht kaum einen Weg. Ob hier ein\nDrache haust?!++
        short: Wald
      en:
        long: in a scary wood.\n++You almost see no path. Is this a place\nwhere dragons live?!++
        short: wood
    directions: 
      - 44
      - 40
      - 42
      - 41
    coordinates:
      y: 2
      x: 7
  43:
    description:
      de:
        long: in einem unheimlichen Wald.\n++Man sieht kaum einen Weg. Ob hier ein\nDrache haust?!++
        short: Wald
      en:
        long: in a scary wood.\n++You almost see no path. Is this a place\nwhere dragons live?!++
        short: wood
    directions: 
      - 47
      - 41
      - 43
      - 43
    coordinates:
      y: 1
      x: 6
  44:
    description:
      de:
        long: in einem unheimlichen Wald.\n++Man sieht kaum einen Weg. Ob hier ein\nDrache haust?!++
        short: Wald
      en:
        long: in a scary wood.\n++You almost see no path. Is this a place\nwhere dragons live?!++
        short: wood
    directions: 
      - 48
      - 42
      - 45
      - 44
    coordinates:
      y: 1
      x: 7
  45:
    description:
      de:
        long: in einem unheimlichen Wald.\n++Man sieht kaum einen Weg. Ob hier ein\nDrache haust?!++
        short: Wald
      en:
        long: in a scary wood.\n++You almost see no path. Is this a place\nwhere dragons live?!++
        short: wood
    directions: 
      - 49
      - 45
      - 45
      - 44
    coordinates:
      y: 1
      x: 8
  46:
    description:
      de:
        long: in einem unheimlichen Wald.\n++Man sieht kaum einen Weg. Ob hier ein\nDrache haust?!++
        short: Wald
      en:
        long: in a scary wood.\n++You almost see no path. Is this a place\nwhere dragons live?!++
        short: wood
    directions: 
      - 50
      - 51
      - 0
      - 0
    coordinates:
      y: 1
      x: 9
  47:
    description:
      de:
        long: in einem unheimlichen Wald.\n++Man sieht kaum einen Weg. Ob hier ein\nDrache haust?!++
        short: Wald
      en:
        long: in a scary wood.\n++You almost see no path. Is this a place\nwhere dragons live?!++
        short: wood
    directions: 
      - 47
      - 43
      - 48
      - 47
    coordinates:
      y: 0
      x: 6
  48:
    description:
      de:
        long: in einem unheimlichen Wald.\n++Man sieht kaum einen Weg. Ob hier ein\nDrache haust?!++
        short: Wald
      en:
        long: in a scary wood.\n++You almost see no path. Is this a place\nwhere dragons live?!++
        short: wood
    directions: 
      - 48
      - 44
      - 48
      - 47
    coordinates:
      y: 0
      x: 7
  49:
    description:
      de:
        long: in einem unheimlichen Wald.\n++Man sieht kaum einen Weg. Ob hier ein\nDrache haust?!++
        short: Wald
      en:
        long: in a scary wood.\n++You almost see no path. Is this a place\nwhere dragons live?!++
        short: wood
    directions: 
      - 0
      - 45
      - 50
      - 0
    coordinates:
      y: 0
      x: 8
  50:
    description:
      de:
        long: in einem unheimlichen Wald.\n++Man sieht kaum einen Weg. Ob hier ein\nDrache haust?!++
        short: Wald
      en:
        long: in a scary wood.\n++You almost see no path. Is this a place\nwhere dragons live?!++
        short: wood
    directions: 
      - 0
      - 46
      - 0
      - 49
    coordinates:
      y: 0
      x: 9
  51:
    description:
      de:
        long: auf einer unzugänglichen Waldlichtung.
        short: Waldlichtung
      en:
        long: on an inaccessible forest glade.
        short: glade
    directions: 
      - 46
      - 0
      - 0
      - 0
    coordinates:
      y: 2
      x: 9
