overwrites:
  - area: 29
    content:
    - " ┏━━━━━━━━━━━━━━━━━┓ "
    - " ┃     Burghof     ┣━"
    - " ┗━━━━━━━ ⯅ ━━━━━━━┛ "

  - area: 30
    content:
    - " ┏━━━━━━━━━━━━━━━━━┓ "
    - "━▶   Burgverlies   ┃ "
    - " ┗━━━━━━━━┳━━━━━━━━┛ "

  - area: 31
    content:
    - "━━━━━━━━━━━┓         "
    - " Baumkrone ┃         "
    - "━━━━━━━━━━━┛         "

  - area: 52
    content:
    - " ┏━━━━━━━━━━━━━━━━━┓ "
    - "━▶    Felswand     ┃ "
    - " ┗━━━━━━━━┳━━━━━━━━┛ "

  - area: 53
    content:
    - "          ┃          "
    - "          ┃          "
    - "          ┃          "

  - area: 54
    content:
    - " ┏━━━━━━━━┻━━━━━━┻━┓ "
    - "━┫     Heide (hoch)┣━"
    - " ┗━━━━━━━━┳━━━━━━━━┛ "

  - area: 55
    content:
    - "          ┃ ┏━━━━━━━━"
    - "          ┃ ┃(runter)"
    - "          ┃ ┗━━━━┳━━━"

  - area: 56
    content:
    - "            ┏━━━━━━━━"
    - "            ┃(runter)"
    - "            ┗━━━━┳━━━"

  - area: 57
    content:
    - " ┏━━━━━━━━┻━━━━━━━━┓ "
    - "━┫      Moor       ◄━"
    - " ┗━━━━━━━━━━━━━━━━━┛ "

  - area: 58
    content:
    - "                     "
    - "━━━━ Pfad            "
    - "                     "

  - area: 59
    content:
    - "          ┃          "
    - "━━▶ Moor  ┃          "
    - "          ┃          "

  - area: 60
    content:
    - "          ┃          "
    - "━━━━━━━━━━┃━━━━━━━━━━"
    - "          ┃          "

  - area: 61
    content:
    - "                     "
    - "                     "
    - "          ┏━┓        "

  - area: 62
    content:
    - " ┏━━━━━━━━┻ ⯆ ━━━━━┓ "
    - "━┫  Dornengestrüpp ┣━"
    - " ┗━━━━━━━━┳━━━━━━━━┛ "

  - area: 63
    content:
    - "┏▶ ━━━━━━━┻━━━━━━━━┓ "
    - "┗┫  Dornengestrüpp ┣┓"
    - " ┗━━━━━ ⯅ ┳━━━━━━━━◄┛ "

  - area: 64
    content:
    - "        ┗━┛          "
    - "                     "
    - "                     "

  - area: 65
    content:
    - " ┏━━━━━━━━┻━━━━━━━━┓ "
    - "━┫  Dornengestrüpp ┣┓"
    - " ┗━━━━━ ⯅ ┳━━━━━━━━◄┛ "

  - area: 66
    content:
    - "┏▶ ━━━━━━━┻━━━━━━━━┓ "
    - "┗┫      Wald       ┣━"
    - " ┗━━━━━ ⯅ ┳━━━━━━━━┛ "

  - area: 67
    content:
    - "        ┗━┛          "
    - "                     "
    - "          ┏━┓        "

  - area: 68
    content:
    - " ┏━━━━━━━━┻━━━━━━━━┓ "
    - "━┫      Wald       ┣┓"
    - " ┗━━━━━━━━┳━━━━━━━━◄┛"

  - area: 69
    content:
    - "┏▶ ━━━━━━━┻━━━━━━━━┓ "
    - "┗┫      Wald       ┣┓"
    - " ┗━━━━━━━━┳━━━━━━━━◄┛"

  - area: 70
    content:
    - "┏▶ ━━━━━━━┻━━━━━━━━┓ "
    - "┗┫      Wald       ┣━"
    - " ┗━━━━━━━━┳━━━━━━━━┛ "

  - area: 71
    content:
    - " ┏━━━━━━━━┻━━━━━━━━┓ "
    - "━┫      Wald       ┣┓"
    - " ┗━━━━━ ⯅ ┳━━━━━━━━◄┛"

  - area: 72
    content:
    - "┏▶ ━━━━━━━━━━━━━━━━┓ "
    - "┗┫      Wald       ┣━"
    - " ┗━━━━━━━━┳━━━━━━━━┛ "

  - area: 73
    content:
    - " ┏━━━━━━━━━━━━━━━━━┓ "
    - "━┫      Wald       ┣┓"
    - " ┗━━━━━━━━┳━━━━━━━━◄┛"
