overwrites:
  - area: 29
    content:
      de:
        - " ┏━━━━━━━━━━━━━━━━━┓ "
        - " ┃     Burghof     ┣━"
        - " ┗━━━━━━━ ⯅ ━━━━━━━┛ "
      en:
        - " ┏━━━━━━━━━━━━━━━━━┓ "
        - " ┃    courtyard    ┣━"
        - " ┗━━━━━━━ ⯅ ━━━━━━━┛ "

  - area: 30
    content:
      de:
        - " ┏━━━━━━━━━━━━━━━━━┓ "
        - "━▶   Burgverlies   ┃ "
        - " ┗━━━━━━━━┳━━━━━━━━┛ "
      en:
        - " ┏━━━━━━━━━━━━━━━━━┓ "
        - "━▶     dungeon     ┃ "
        - " ┗━━━━━━━━┳━━━━━━━━┛ "

  - area: 31
    content:
      de:
        - "━━━━━━━━━━━┓         "
        - "mkrone     ┃         "
        - "━━━━━━━━━━━┛         "
      en:
        - "━━━━━━━━━━━┓         "
        - " top       ┃         "
        - "━━━━━━━━━━━┛         "

  - area: 52
    content:
      de:
        - " ┏━━━━━━━━━━━━━━━━━┓ "
        - "━▶    Felswand     ┃ "
        - " ┗━━━━━━━━┳━━━━━━━━┛ "
      en:
        - " ┏━━━━━━━━━━━━━━━━━┓ "
        - "━▶     cliff       ┃ "
        - " ┗━━━━━━━━┳━━━━━━━━┛ "

  - area: 53
    content:
      de:
        - "          ┃          "
        - "          ┃          "
        - "          ┃          "
      en:
        - "          ┃          "
        - "          ┃          "
        - "          ┃          "

  - area: 54
    content:
      de:
        - " ┏━━━━━━━━┻━━━━━━┻━┓ "
        - "━┫      Heide      ┣━"
        - " ┗━━━━━━━━┳━━━━━━━━┛ "
      en:
        - " ┏━━━━━━━━┻━━━━━━┻━┓ "
        - "━┫      heath      ┣━"
        - " ┗━━━━━━━━┳━━━━━━━━┛ "

  - area: 55
    content:
      de:
        - "          ┃ ┏━━━━━━━━"
        - "          ┃ ┃     Bau"
        - "          ┃ ┗━━━━┳━━━"
      en:
        - "          ┃ ┏━━━━━━━━"
        - "          ┃ ┃    tree"
        - "          ┃ ┗━━━━┳━━━"

  - area: 56
    content:
      de:
        - "            ┏━━━━━━━━"
        - "            ┃     Bau"
        - "            ┗━━━━┳━━━"
      en:
        - "            ┏━━━━━━━━"
        - "            ┃    tree"
        - "            ┗━━━━┳━━━"

  - area: 57
    content:
      de:
        - " ┏━━━━━━━━┻━━━━━━━━┓ "
        - "━┫      Moor       ◄━"
        - " ┗━━━━━━━━━━━━━━━━━┛ "
      en:
        - " ┏━━━━━━━━┻━━━━━━━━┓ "
        - "━┫      swamp      ◄━"
        - " ┗━━━━━━━━━━━━━━━━━┛ "

  - area: 58
    content:
      de:
        - "                     "
        - "━━━━ Pfad            "
        - "                     "
      en:
        - "                     "
        - "━━━━ path            "
        - "                     "

  - area: 59
    content:
      de:
        - "          ┃          "
        - "━━▶ Moor  ┃          "
        - "          ┃          "
      en:
        - "          ┃          "
        - "━━▶ swamp ┃          "
        - "          ┃          "

  - area: 60
    content:
      de:
        - "          ┃          "
        - "━━━━━━━━━━┃━━━━━━━━━━"
        - "          ┃          "
      en:
        - "          ┃          "
        - "━━━━━━━━━━┃━━━━━━━━━━"
        - "          ┃          "

  - area: 61
    content:
      de:
        - "                     "
        - "                     "
        - "          ┏━┓        "
      en:
        - "                     "
        - "                     "
        - "          ┏━┓        "

  - area: 62
    content:
      de:
        - " ┏━━━━━━━━┻ ⯆ ━━━━━┓ "
        - "━┫  Dornengestrüpp ┣━"
        - " ┗━━━━━━━━┳━━━━━━━━┛ "
      en:
        - " ┏━━━━━━━━┻ ⯆ ━━━━━┓ "
        - "━┫     thicket     ┣━"
        - " ┗━━━━━━━━┳━━━━━━━━┛ "

  - area: 63
    content:
      de:
        - "┏▶ ━━━━━━━┻━━━━━━━━┓ "
        - "┗┫  Dornengestrüpp ┣┓"
        - " ┗━━━━━ ⯅ ┳━━━━━━━━◄┛"
      en:
        - "┏▶ ━━━━━━━┻━━━━━━━━┓ "
        - "┗┫     thicket     ┣┓"
        - " ┗━━━━━ ⯅ ┳━━━━━━━━◄┛"

  - area: 64
    content:
      de:
        - "        ┗━┛          "
        - "                     "
        - "                     "
      en:
        - "        ┗━┛          "
        - "                     "
        - "                     "

  - area: 65
    content:
      de:
        - " ┏━━━━━━━━┻━━━━━━━━┓ "
        - "━┫  Dornengestrüpp ┣┓"
        - " ┗━━━━━ ⯅ ┳━━━━━━━━◄┛"
      en:
        - " ┏━━━━━━━━┻━━━━━━━━┓ "
        - "━┫     thicket     ┣┓"
        - " ┗━━━━━ ⯅ ┳━━━━━━━━◄┛"

  - area: 66
    content:
      de:
        - "┏▶ ━━━━━━━┻━━━━━━━━┓ "
        - "┗┫      Wald       ┣━"
        - " ┗━━━━━ ⯅ ┳━━━━━━━━┛ "
      en:
        - "┏▶ ━━━━━━━┻━━━━━━━━┓ "
        - "┗┫      wood       ┣━"
        - " ┗━━━━━ ⯅ ┳━━━━━━━━┛ "

  - area: 67
    content:
      de:
        - "        ┗━┛          "
        - "                     "
        - "          ┏━┓        "
      en:
        - "        ┗━┛          "
        - "                     "
        - "          ┏━┓        "

  - area: 68
    content:
      de:
        - " ┏━━━━━━━━┻━━━━━━━━┓ "
        - "━┫      Wald       ┣┓"
        - " ┗━━━━━━━━┳━━━━━━━━◄┛"
      en:
        - " ┏━━━━━━━━┻━━━━━━━━┓ "
        - "━┫      wood       ┣┓"
        - " ┗━━━━━━━━┳━━━━━━━━◄┛"

  - area: 69
    content:
      de:
        - "┏▶ ━━━━━━━┻━━━━━━━━┓ "
        - "┗┫      Wald       ┣┓"
        - " ┗━━━━━━━━┳━━━━━━━━◄┛"
      en:
        - "┏▶ ━━━━━━━┻━━━━━━━━┓ "
        - "┗┫      wood       ┣┓"
        - " ┗━━━━━━━━┳━━━━━━━━◄┛"

  - area: 70
    content:
      de:
        - "┏▶ ━━━━━━━┻━━━━━━━━┓ "
        - "┗┫      Wald       ┣━"
        - " ┗━━━━━━━━┳━━━━━━━━┛ "
      en:
        - "┏▶ ━━━━━━━┻━━━━━━━━┓ "
        - "┗┫      wood       ┣━"
        - " ┗━━━━━━━━┳━━━━━━━━┛ "

  - area: 71
    content:
      de:
        - " ┏━━━━━━━━┻━━━━━━━━┓ "
        - "━┫      Wald       ┣┓"
        - " ┗━━━━━ ⯅ ┳━━━━━━━━◄┛"
      en:
        - " ┏━━━━━━━━┻━━━━━━━━┓ "
        - "━┫      wood       ┣┓"
        - " ┗━━━━━ ⯅ ┳━━━━━━━━◄┛"

  - area: 72
    content:
      de:
        - "┏▶ ━━━━━━━━━━━━━━━━┓ "
        - "┗┫      Wald       ┣━"
        - " ┗━━━━━━━━┳━━━━━━━━┛ "
      en:
        - "┏▶ ━━━━━━━━━━━━━━━━┓ "
        - "┗┫      wood       ┣━"
        - " ┗━━━━━━━━┳━━━━━━━━┛ "

  - area: 73
    content:
      de:
        - " ┏━━━━━━━━━━━━━━━━━┓ "
        - "━┫      Wald       ┣┓"
        - " ┗━━━━━━━━┳━━━━━━━━◄┛"
      en:
        - " ┏━━━━━━━━━━━━━━━━━┓ "
        - "━┫      wood       ┣┓"
        - " ┗━━━━━━━━┳━━━━━━━━◄┛"
