nouns:
  - N
  - S
  - O
  - W
  - Norden
  - Süden
  - Osten
  - Westen

#   - Zauberkuchen
#   - Raupe
#   - Buch
#   - Zettel
#   - Tarnkappe
#   - Riesenfrucht
#   - Feuerschwert
#   - Bär
#   - Schild
#   - Zwerg
#   - Dracheneier
#   - Stein
#   - Hölenmalerei
#   - Strauch
#   - Beeren
#   - Blätter
#   - Diamantmesser
#   - Silberschlüssel
#   - Baum
#   - Pergament
#   - Steinschleuder
#   - Wasserkrug
#   - Zauberschuhe
#   - Schrifttafel
#   - Zwergendolch
#   - Kugel
#   - Kästchen
#   - Gnom
#   - Ring
#   - Brief
#   - Rubin
#   - Tür
#   - Feenhaar
#   - Drache
#   - Holztafel
#   - Pokal