objects:
  9:
    description:
      long: einen Zauberkuchen
      short: Zauberkuchen
      alt: Kuchen
      article: der
    area: 28
    value: 0
  10:
    description:
      long: eine haarige Raupe
      short: Raupe
      article: die
    area: 29
    value: 0
  11:
    description:
      long: ein grünes Buch
      short: Buch
      article: das
    area: 8
    value: 0
  12:
    description:
      long: einen Zettel
      short: Zettel
      article: der
    area: 24
    value: 0
  13:
    description:
      long: eine Tarnkappe
      short: Tarnkappe
      alt: Kappe
      article: die
    area: 2
    value: 0
  14:
    description:
      long: eine Riesenfrucht 
      short: Riesenfrucht
      alt: Frucht
      article: die
    area: 26
    value: 0
  15:
    description:
      long: "::ein Feuerschwert::"
      short: Feuerschwert
      alt: Schwert
      article: das
    area: 20
    value: 10
  16:
    description:
      long:  einen grossen Bären
      short: Bär
      article: der
    area: 19
    value: 0
  17:
    description:
      long: "::einen Schild aus bronze::"
      short: Schild
      article: der
    area: 19
    value: 22
  18:
    description:
      long: einen Zwerg
      short: Zwerg
      article: der
    area: 18
    value: 0
  19:
    description:
      long: "::goldene Dracheneier::"
      short: Dracheneier
      alt: Eier
      article: die
    area: 18
    value: 20
  20:
    description:
      long: einen Stein 
      short: Stein
      article: der
    area: 16
    value: 0
  21:
    description:
      long: eine Hölenmalerei 
      short: Hölenmalerei
      alt: Malerei
      article: die
    area: 13
    value: 0
  22:
    description:
      long: einen hässlichen Strauch 
      short: Strauch
      article: der
    area: 14
    value: 0
  23:
    description:
      long: viele rote Beeren 
      short: Beeren
      article: die
    area: 0
    value: 0
  24:
    description:
      long: "::goldene Blätter::"
      short: Blätter
      article: die
    area: 0
    value: 26
  25:
    description:
      long: "::ein Diamantmesser::"
      short: Diamantmesser
      alt: Messer
      article: das
    area: 15
    value: 5
  26:
    description:
      long: "::einen Silberschlüssel::"
      short: Silberschlüssel
      alt: Schlüssel
      article: der
    area: 8
    value: 5
  27:
    description:
      long: einen dürren Baum 
      short: Baum
      article: der
    area: 9
    value: 0
  28:
    description:
      long: ein vergilbtes Pergament 
      short: Pergament
      article: das
    area: 11
    value: 0
  29:
    description:
      long: eine grosse Steinschleuder 
      short: Steinschleuder
      alt: Schleuder
      article: die
    area: 12
    value: 0
  30:
    description:
      long: einen leeren Wasserkrug 
      short: Wasserkrug
      alt: Krug
      article: der
    area: 1
    value: 0
  31:
    description:
      long: ein Paar Zauberschuhe 
      short: Zauberschuhe
      alt: Schuhe
      article: die
    area: 1
    value: 0
  32:
    description:
      long: eine Schrifttafel 
      short: Schrifttafel
      alt: Tafel
      article: die
    area: 1
    value: 0
  33:
    description:
      long: "::einen Zwergendolch::"
      short: Zwergendolch
      alt: Dolch
      article: der
    area: 3
    value: 7
  34:
    description:
      long: eine grosse Kugel 
      short: Kugel
      article: die
    area: 4
    value: 0
  35:
    description:
      long: ein rotes Kästchen 
      short: Kästchen
      article: das
    area: 4
    value: 0
  36:
    description:
      long: einen bösen Gnom 
      short: Gnom
      article: der
    area: 4
    value: 0
  37:
    description:
      long: einen eisernen Ring 
      short: Ring
      article: der
    area: 0
    value: 0
  38:
    description:
      long: einen Brief 
      short: Brief
      article: der
    area: 0
    value: 0
  39:
    description:
      long: "::einen roten Rubin::"
      short: Rubin
      article: der
    area: 0
    value: 18
  40:
    description:
      long: eine Tür im Norden 
      short: Tür
      article: die
    area: 25
    value: 0
  45:
    description:
      long: eine Tür im Süden 
      short: Tür
      article: die
    area: 30
    value: 0
  41:
    description:
      long: "::goldenes Feenhaar::"
      short: Feenhaar
      alt: Haar
      article: das
    area: 33
    value: 10
  42:
    description:
      long: einen feuerspeienden Drachen 
      short: Drachen
      article: der
    area: 51
    value: 0
  43:
    description:
      long: eine verwitterte Holztafel 
      short: Holztafel
      alt: Tafel
      article: die
    area: 40
    value: 0
  44:
    description:
      long: "::einen silbernen Pokal::"
      short: Pokal
      article: der
    area: 51
    value: 47
  46:
    description:
      long: "::eine goldene Kugel::" 
      short: Kugel
      article: die
    area: 0
    value: 11
  47:
    description:
      long: "eine verbleichte Landkarte" 
      short: Landkarte
      alt: Karte
      article: die
    area: 31
    value: 0
  48:
    description:
      long: "ein unbekannter Gegenstand"
      short: Gegenstand
      alt: Gegenstand
      article: der
    area: 0
    value: 0