verbs:
  - gehe
  - stich
  - sieh
  - inventar
  - save
  - load
  - fantasia
  - ende
  - wirf
  - töte
  - lies
  - fülle
  - öffne
  - benutze
  - simsalabim
  - sage
  - gieße
  - schieße
  - füttere
  - schneide
  - sperre
  - hilfe
  - klettere
  - schleudere
  - iss
  - nimm
  - verjage
  - lege
  - drehe
  - springe
  - trinke