conditions:
  door:
    south: a door in the south
    north: a door in the north
  jar:
    full: a full jar
    empty: an empty jar
  ring:
    golden: "::a ring made of golden threads::"
  bush:
    ugly: an ugly bush
    watered: a beautiful bush
  fango:
    the: "a ::besmirched:: %s"