overwrites:
  - area: 29
    content:
    - " ┏━━━━━━━━━━━━━━━━━┓ "
    - " ┃    courtyard    ┣━"
    - " ┗━━━━━━━ ⯅ ━━━━━━━┛ "

  - area: 30
    content:
    - " ┏━━━━━━━━━━━━━━━━━┓ "
    - "━▶     dungeon     ┃ "
    - " ┗━━━━━━━━┳━━━━━━━━┛ "

  - area: 31
    content:
    - "━━━━━━━━━━━┓         "
    - " top       ┃         "
    - "━━━━━━━━━━━┛         "

  - area: 52
    content:
    - " ┏━━━━━━━━━━━━━━━━━┓ "
    - "━▶     cliff       ┃ "
    - " ┗━━━━━━━━┳━━━━━━━━┛ "

  - area: 53
    content:
    - "          ┃          "
    - "          ┃          "
    - "          ┃          "

  - area: 54
    content:
    - " ┏━━━━━━━━┻━━━━━━┻━┓ "
    - "━┫      heath      ┣━"
    - " ┗━━━━━━━━┳━━━━━━━━┛ "

  - area: 55
    content:
    - "          ┃ ┏━━━━━━━━"
    - "          ┃ ┃    tree"
    - "          ┃ ┗━━━━┳━━━"

  - area: 56
    content:
    - "            ┏━━━━━━━━"
    - "            ┃    tree"
    - "            ┗━━━━┳━━━"

  - area: 57
    content:
    - " ┏━━━━━━━━┻━━━━━━━━┓ "
    - "━┫      swamp      ◄━"
    - " ┗━━━━━━━━━━━━━━━━━┛ "

  - area: 58
    content:
    - "                     "
    - "━━━━ path            "
    - "                     "

  - area: 59
    content:
    - "          ┃          "
    - "━━▶ swamp ┃          "
    - "          ┃          "

  - area: 60
    content:
    - "          ┃          "
    - "━━━━━━━━━━┃━━━━━━━━━━"
    - "          ┃          "

  - area: 61
    content:
    - "                     "
    - "                     "
    - "          ┏━┓        "

  - area: 62
    content:
    - " ┏━━━━━━━━┻ ⯆ ━━━━━┓ "
    - "━┫     thicket     ┣━"
    - " ┗━━━━━━━━┳━━━━━━━━┛ "

  - area: 63
    content:
    - "┏▶ ━━━━━━━┻━━━━━━━━┓ "
    - "┗┫     thicket     ┣┓"
    - " ┗━━━━━ ⯅ ┳━━━━━━━━◄┛ "

  - area: 64
    content:
    - "        ┗━┛          "
    - "                     "
    - "                     "

  - area: 65
    content:
    - " ┏━━━━━━━━┻━━━━━━━━┓ "
    - "━┫     thicket     ┣┓"
    - " ┗━━━━━ ⯅ ┳━━━━━━━━◄┛ "

  - area: 66
    content:
    - "┏▶ ━━━━━━━┻━━━━━━━━┓ "
    - "┗┫      wood       ┣━"
    - " ┗━━━━━ ⯅ ┳━━━━━━━━┛ "

  - area: 67
    content:
    - "        ┗━┛          "
    - "                     "
    - "          ┏━┓        "

  - area: 68
    content:
    - " ┏━━━━━━━━┻━━━━━━━━┓ "
    - "━┫      wood       ┣┓"
    - " ┗━━━━━━━━┳━━━━━━━━◄┛"

  - area: 69
    content:
    - "┏▶ ━━━━━━━┻━━━━━━━━┓ "
    - "┗┫      wood       ┣┓"
    - " ┗━━━━━━━━┳━━━━━━━━◄┛"

  - area: 70
    content:
    - "┏▶ ━━━━━━━┻━━━━━━━━┓ "
    - "┗┫      wood       ┣━"
    - " ┗━━━━━━━━┳━━━━━━━━┛ "

  - area: 71
    content:
    - " ┏━━━━━━━━┻━━━━━━━━┓ "
    - "━┫      wood       ┣┓"
    - " ┗━━━━━ ⯅ ┳━━━━━━━━◄┛"

  - area: 72
    content:
    - "┏▶ ━━━━━━━━━━━━━━━━┓ "
    - "┗┫      wood       ┣━"
    - " ┗━━━━━━━━┳━━━━━━━━┛ "

  - area: 73
    content:
    - " ┏━━━━━━━━━━━━━━━━━┓ "
    - "━┫      wood       ┣┓"
    - " ┗━━━━━━━━┳━━━━━━━━◄┛"
