objects:
  9:
    description:
      long: a magic cake
      short: cake
      article: the
    area: 28
    value: 0
  10:
    description:
      long: a hairy grub
      short: grub
      article: the
    area: 29
    value: 0
  11:
    description:
      long: a green book
      short: book
      article: the
    area: 8
    value: 0
  12:
    description:
      long: a slip of paper
      short: slip
      alt: paper
      article: the
    area: 24
    value: 0
  13:
    description:
      long: a magic hood
      short: hood
      article: the
    area: 2
    value: 0
  14:
    description:
      long: a giant fruit
      short: fruit
      article: the
    area: 26
    value: 0
  15:
    description:
      long: "::a fire sword::"
      short: sword
      article: the
    area: 20
    value: 10
  16:
    description:
      long:  a big baer
      short: baer
      article: the
    area: 19
    value: 0
  17:
    description:
      long: "::a buckler made of bronze::"
      short: buckler
      article: the
    area: 19
    value: 22
  18:
    description:
      long: a dwarf
      short: dwarf
      article: the
    area: 18
    value: 0
  19:
    description:
      long: "::golden dragon eggs::"
      short: eggs
      article: the
    area: 18
    value: 20
  20:
    description:
      long: a stone
      short: stone
      article: the
    area: 16
    value: 0
  21:
    description:
      long: a wall painting
      short: painting
      article: the
    area: 13
    value: 0
  22:
    description:
      long: an ugly bush
      short: bush
      article: the
    area: 14
    value: 0
  23:
    description:
      long: a lot of red berries
      short: berries
      article: the
    area: 0
    value: 0
  24:
    description:
      long: "::golden leaves::"
      short: leaves
      article: the
    area: 0
    value: 26
  25:
    description:
      long: "::a diamond knive::"
      short: knive
      article: the
    area: 15
    value: 5
  26:
    description:
      long: "::a silver key::"
      short: key
      article: the
    area: 8
    value: 5
  27:
    description:
      long: a brittle tree
      short: tree
      article: the
    area: 9
    value: 0
  28:
    description:
      long: a yellowed parchment
      short: parchment
      article: the
    area: 11
    value: 0
  29:
    description:
      long: a big catapult
      short: catapult
      article: the
    area: 12
    value: 0
  30:
    description:
      long: an empty jar
      short: jar
      article: the
    area: 1
    value: 0
  31:
    description:
      long: a pair of wizard shoes
      short: shoes
      article: the
    area: 1
    value: 0
  32:
    description:
      long: a sign board
      short: board
      alt: sign
      article: the
    area: 1
    value: 0
  33:
    description:
      long: "::a dwarf dagger::"
      short: dagger
      article: the
    area: 3
    value: 7
  34:
    description:
      long: a big shpere
      short: shpere
      article: the
    area: 4
    value: 0
  35:
    description:
      long: a red box
      short: box
      article: the
    area: 4
    value: 0
  36:
    description:
      long: an evil gnome
      short: gnome
      article: the
    area: 4
    value: 0
  37:
    description:
      long: an iron ring
      short: ring
      article: the
    area: 0
    value: 0
  38:
    description:
      long: a letter
      short: letter
      article: the
    area: 0
    value: 0
  39:
    description:
      long: "::a red ruby::"
      short: ruby
      article: the
    area: 0
    value: 18
  40:
    description:
      long: a door in the north
      short: door
      article: the
    area: 25
    value: 0
  45:
    description:
      long: a door in the south
      short: door
      article: the
    area: 30
    value: 0
  41:
    description:
      long: "::a golden hair of a fairy::"
      short: hair
      article: the
    area: 33
    value: 10
  42:
    description:
      long: a fire breathing dragon
      short: dragon
      article: the
    area: 51
    value: 0
  43:
    description:
      long: a rotten board
      short: board
      article: the
    area: 40
    value: 0
  44:
    description:
      long: "::a silver goblet::"
      short: goblet
      article: the
    area: 51
    value: 47
  46:
    description:
      long: "::a golden sphere::" 
      short: sphere
      article: the
    area: 0
    value: 11
  47:
    description:
      long: "a faded country map" 
      short: map
      article: the
    area: 31
    value: 0
  48:
    description:
      long: "an unknown item"
      short: item
      article: the
    area: 0
    value: 0
  49:
    description:
      long: "a fango package"
      short: package
      alt: fango
      article: the
    area: 5
    value: 0