reactions:
  silly:
    statement:
      - "Dont't be silly."
      - "Right ..."
      - "I don't think so."
      - "Nice try ...."
    ok: false
    ko: false
    color: RED
  noTool:
    statement:
      - "I don't have the fitting tools."
    ok: false
    ko: false
    color: RED
  dontKnowHow:
    statement:
      - "I don't know how to do this."
      - "How should this work?"
    ok: false
    ko: false
    color: RED
  wontLet:
    statement:
      - "is blocking me."
    ok: false
    ko: false
    color: RED
  tooHeavy:
    statement:
      - "Too heavy."
    ok: false
    ko: false
    color: RED
  unreachable:
    statement:
      - "I can't reach it."
      - "My arms are to short."
    ok: false
    ko: false
    color: RED
  invFull:
    statement: 
      - |
        I am carrying to much.
        I have to put something down.
    ok: false
    ko: false
    color: RED
  ok:
    statement:
      - "Done."
      - "Okay."
      - "As you command."
      - "Roger."
    ok: true
    ko: false
    color: GREEN
  noWay:
    statement:
      - "There is no way in this direction."
      - "No way!"
      - "Only the given directions ...."
    ok: false
    ko: false
    color: RED
  noShoes:
    statement:
      - "Help...\n\nI am sinking in the ground."
    ok: false
    ko: true
    color: RED
  locked:
    statement:
      - "The door is closed."
    ok: false
    ko: false
    color: RED
  tryCut:
    statement:
      - "Try cut."
    ok: true
    ko: false
    color: GREEN
  stabGrub:
    statement:
      - "The grub is tickelish and starts laughing loud!"
    ok: true
    ko: false
    color: GREEN
  stabBear:
    statement:
      - "The baer growls reluctantly."
    ok: true
    ko: false
    color: GREEN
  stabDwarf:
    statement:
      - "The dwarf gets angry and kills me!"
    ok: false
    ko: true
    color: RED
  stabDwarfHooded:
    statement:
      - "The dwarf gets scared and tries to hit me, but misses.\n\nThe magic hood disolves into thin air!"
    ok: false
    ko: false
    color: RED
  stabGnome:
    statement:
      - "The gnome bewitches me.!"
    ok: false
    ko: true
    color: RED
  stabGnomeHooded:
    statement:
      - "The gnome gets scared and starts swearing.\n\nThe magic hood disolves into thin air!"
    ok: false
    ko: false
    color: RED
  stabDragon:
    statement:
      - "The dragon burns me alive!"
    ok: false
    ko: true
    color: RED
  dontSee:
    statement:
      - "I dont't see this."
    ok: false
    ko: false
    color: RED
  haveAlready:
    statement:
      - "I already have this."
    ok: true
    ko: false
    color: GREEN
  dontHave:
    statement:
      - "I don't have this with me."
    ok: false
    ko: false
    color: RED
  invEmpty:
    statement:
      - "I have have nothing with me."
    ok: true
    ko: false
    color: RED
  inv:
    statement:
      - "I have:"
    ok: true
    ko: false
    color: GREEN
  useHood:
    statement:
      - "Done. I put on the magic hood."
    ok: true
    ko: false
    color: GREEN
  hoodInUse:
    statement:
      - "The magic hood disolves into thin air!"
    ok: false
    ko: false
    color: RED
  useShoes:
    statement:
      - "Okay. I put on the wizard shoes."
    ok: true
    ko: false
    color: GREEN
  unknownVerb:
    statement:
      - |
        I don't know '%s'.
        The command 'verbs' gives you a list of all the verbs I know.
    ok: true
    ko: false
    color: RED
  unknownNoun:
    statement:
      - "I don't know '%s'."
      - "'%s' will be in store tomorrow again."
      - "%s?"
    ok: false
    ko: false
    color: RED
  needObject:
    statement:
      - "Please add an object."
    ok: false
    ko: false
    color: RED
  inTheMoor:
    statement:
      - "I lost everythin I was carrying in the swamp!"
    ok: true
    ko: false
    color: RED
  noSaveFile:
    statement:
      - "There is so saved game."
    ok: false
    ko: false
    color: RED
  loaded:
    statement:
      - "Game successfully loaded."
    ok: true
    ko: false
    color: GREEN
  saved:
    statement:
      - "Game successfully saved."
    ok: true
    ko: false
    color: GREEN
  squashed:
    statement:
      - |
        The sphere squashes the gnome and
        turns to gold.
    ok: true
    ko: false
    color: GREEN
  brokenSphere:
    statement:
      - "The sphere falls to the ground and shatters."
    ok: false
    ko: false
    color: RED
  throwObject:
    statement:
      - "Out of sight, out of mind.\n%s %s is now %s."
      - "Wow new throwing record.\n%s %s is now %s."
      - "Zadong ...\nand gone.\n%s %s is now %s." 
    ok: true
    ko: false
    color: GREEN
  throwFixedObject:
    statement:
      - "Brilliant idea!"
    ok: false
    ko: false
    color: RED
  nothingWritten:
    statement:
      - "There is nothing written on it."
    ok: false
    ko: false
    color: RED
  book:
    statement:
      - |
        The book says:
        Knives are for stabbing!
    ok: true
    ko: false
    color: GREEN
  paper:
    statement:
      - |
        The slip of paper says:
        You can't chase dragons away.
        They are invulnerable and immortal!
    ok: true
    ko: false
    color: GREEN
  shield:
    statement:
      - |
        Engraved in the buckler is:
        Things spin around rings!
    ok: true
    ko: false
    color: GREEN
  wallpainting:
    statement:
      - |
        The wall painting says:
                 Some wizard was here.
                      Simsalabim!
    ok: true
    ko: false
    color: GREEN
  parchment:
    statement:
      - |
        The parchmet says:
        Long time ago birds have been enchanted into dwarfs.
    ok: true
    ko: false
    color: GREEN
  panel:
    statement:
      - |
        The board says:
        Foreigner who enters this realm,
        search for the lost ::treasures::!
        Bring them here and put them down.
        Say 'Fangotasia'!
    ok: true
    ko: false
    color: GREEN
  letter:
    statement:
      - |
        The letter says:
        Plants need water!
    ok: true
    ko: false
    color: GREEN
  rottenPanel:
    statement:
      - |
        The writing on the board is almost gone:
        Beware of the dragon!
    ok: true
    ko: false
    color: GREEN
  missMap:
    statement:
      - "Oops. Missed this time."
    ok: true
    ko: false
    color: RED
  hitMap:
    statement:
      - "The stone hits the map and both fall to the ground."
    ok: true
    ko: false
    color: GREEN
  readMap:
    statement:
      - "The map shows all areas I already have been to."
    ok: true
    ko: false
    color: GREEN
  useMap:
    statement:
      - |
        Perfect.
        Now I can see where I am and where I have been.
        Now I know the word "map".
        Say 'map'.
    ok: true
    ko: false
    color: GREEN
  noKey:
    statement:
      - "I don't have a key."
    ok: false
    ko: false
    color: RED
  openBox:
    statement:
      - "Two things fall out."
    ok: true
    ko: false
    color: GREEN
  alreadyOpen:
    statement:
      - "It's already open."
    ok: true
    ko: false
    color: GREEN
  say:
    statement:
      - "'%s'\n...\n...\nNothing happens."
    ok: true
    ko: false
    color: GREEN
  simsalabim:
    statement:
      - "The dwarf turns into a colorful bird\nand flies away!"
    ok: true
    ko: false
    color: GREEN
  unusable:
    statement:
      - "Really?\nYou want me to fill %s with Water?\nThink again!"
    ok: false
    ko: false
    color: RED
  unsuitable:
    statement:
      - "%s is unsuitable for this."
    ok: false
    ko: false
    color: RED
  noWater:
    statement:
      - "There is no water far and wide."
    ok: false
    ko: false
    color: RED
  waterUnreachable:
    statement:
      - "I can't reach the water."
    ok: false
    ko: false
    color: RED
  feed:
    statement:
      - "%s is not hungry."
    ok: false
    ko: false
    color: RED
  feedBaer:
    statement:
      - "The baer is very hungry and starts eating\n... \nme!"
    ok: false
    ko: true
    color: RED
  feedBaerWithBerries:
    statement:
      - "The baer swallows the berreies and walks away."
    ok: true
    ko: false
    color: GREEN
  cutFruit:
    statement:
      - "I split the fruit and something falls out."
    ok: true
    ko: false
    color: GREEN
  fruitAlreadyCut:
    statement:
      - "The fruit is already split."
    ok: true
    ko: false
    color: GREEN
  tryThrow:
    statement:
      - "Try 'throw'."
    ok: true
    ko: false
    color: GREEN
  eatCake:
    statement:
      - "Brrrrr! Tastes horrible!\nNow I feel very strong!"
    ok: true
    ko: false
    color: GREEN
  drinkJar:
    statement:
      - "Aaaaaah good!"
    ok: true
    ko: false
    color: GREEN
  jarEmpty:
    statement:
      - "The jar is empty."
    ok: false
    ko: false
    color: RED
  cantEat:
    statement:
      - "Of course! And what do I drink? Pangalatic Gargle Blaster?"
    ok: false
    ko: false
    color: RED
  spin:
    statement:
      - "Okay.\n...\nNothing happens."
    ok: true
    ko: false
    color: GREEN
  dontSpin:
    statement:
      - "Won't spin."
    ok: false
    ko: false
    color: RED
  spinRing:
    statement:
      - "Everything starts spinning around me!\n\nThe ring falls out of my hand!"
    ok: true
    ko: false
    color: RED
  noJar:
    statement:
      - "I have nothing to water with."
    ok: false
    ko: false
    color: RED
  waterBush:
    statement:
      - "The bush starts blooming and\ngrows red berries.\nThen the bush starts turning."
    ok: true
    ko: false
    color: GREEN
  looksGood:
    statement:
      - "Loogs awsome!"
      - "impressive"
      - "Isn't that a ....\n... well, maybe not."
    ok: true
    ko: false
    color: GREEN
  takeImke:
    statement:
      - "I can't take %s just like that.\n\n%s is here and I can rejoice in it."
    ok: true
    ko: false
    color: GREEN
  scare:
    statement:
      - "%s can't be scared away."
    ok: false
    ko: false
    color: RED
  jump:
    statement:
      - "Bounce....bounce...bounce."
    ok: true
    ko: false
    color: GREEN
  jumpTree:
    statement:
      - "Plump..ouch!\n\nI fell to the ground."
    ok: false
    ko: true
    color: RED
  throwFango:
    statement:
      - "Clap .... a fango patty!"
      - "No suitable targed around."
      - "Better luck next time."
    ok: true
    ko: false
    color: GREEN
  hitWithFango:
    statement:
      - "Clap .... a hit!"
      - "veni, vidi, vici"
      - "Be silly!!"
      - "Fango Tango."
    ok: true
    ko: false
    color: GREEN
  alreadyFangoed:
    statement:
      - "Fango on Fango"
      - "More is not possible."
      - "Has enough already."
    ok: true
    ko: false
    color: GREEN
