elements:
  iAm: I am
  iSee: I see
  directions: Directions
  next: Next
  andNow: and now
  nextYesNo: Next (y/n)?
  yesShort: y
  north: north
  south: south
  east: east
  west: west
  verbsKnown: Verbs, I know
  imke: the pink diamond
  gameOver: G A M E    O V E R
  haveFound: You have found
  points: points
  movesNeeded: "You needed less than %d moves: 10 points"
  visitedMoore: "- You have been to the swamp: %d points"
  visitedCastle: "- You have visited the castle: %d points"
  climbedTree: "- Du bist auf einen Baum geklettert: %d Punkte"
  pointsOutOf: "You have %d of 220 points!"
  oneMoreGame:  "One more game? (y/n)"
  comeOn: "Come on, five more minutes? (y/n)"
  intro: |
    [blue:black:-]Set out for the perilous journey to
    the magical realm of Fangotasia and search
    for legendary treasures.
    Command me with simple commands in
    one or two words like:
    
    [yellow:black:b]JUMP          USE HOOD            END
    
    PUT RUBY       FEED DRAGON       INVENTORY
    
    [white:black:b]SAVE [blue:black:-]the current game, or
    [white:black:b]LOAD [blue:black:-]a previous one.
  prelude: |
    [red:black:b]F A N G O T A S I A
    
    [blue:black:b]- An Adventure from Klaus Hartmuth (1984) -
    
    [yellow:black:b]- GO Version from Tom Hutter (2020) -
