verbs:
  - name: stab
    func: Stab
    single: false
  - name: look
    func: Look
    single: false
  - name: inventory
    func: Inventory
    single: true
  - name: inv
    func: Inventory
    single: true
  - name: save
    func: Save
    single: false
  - name: load
    func: Load
    single: false
  - name: end
    func: End
    single: true
  - name: throw
    func: Throw
    single: false
  - name: read
    func: Read
    single: false
  - name: fill
    func: Fill
    single: false
  - name: open
    func: Open
    single: false
  - name: use
    func: Use
    single: false
  - name: say
    func: Say
    single: false
  - name: water
    func: Water
    single: false
  - name: feed
    func: Feed
    single: false
  - name: cut
    func: Cut
    single: false
  - name: help
    func: Help
    single: false
  - name: climb
    func: Climb
    single: false
  - name: catapult
    func: Catapult
    single: false
  - name: eat
    func: Eat
    single: false
  - name: take
    func: Take
    single: false
  - name: get
    func: Take
    single: false
  - name: scare
    func: Scare
    single: false
  - name: put
    func: Put
    single: false
  - name: spin
    func: Spin
    single: false
  - name: jump
    func: Jump
    single: false
  - name: dink
    func: Drink
    single: false
  - name: verbs
    func: Verbs
    single: true
  - name: n
    func: Move
    single: false
  - name: s
    func: Move
    single: false
  - name: e
    func: Move
    single: false
  - name: w
    func: Move
    single: false
  - name: map
    func: Map
    single: false
