conditions:
  door:
    south: eine Tür im Süden
    north: eine Tür im Norden
  jar:
    full: einen vollen Wasserkrug
    empty: einen leeren Wasserkrug
  ring:
    golden: "::ein Ring aus Goldfäden::"
  bush:
    ugly: einen hässlichen Strauch
    watered: einen edlen Strauch
  fango:
    die: "eine ::besudelte:: %s"
    der: "einen ::besudelten:: %s"
    das: "ein ::besudeltes:: %s"